name: YouTube Live
on:
  schedule:
    - cron: '0 0/2 * * *'

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get beINSportsHaber
      run: |
        touch ./spor/beinsportshaber.m3u8
        sudo cat >./spor/beinsportshaber.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/beinsportsturkiye/live)
        EOL

    - name: Get ASpor
      run: |
        touch ./spor/aspor.m3u8
        sudo cat >./spor/aspor.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@ASpor/live)
        EOL

    - name: Get TayTv
      run: |
        touch ./spor/taytv.m3u8
        sudo cat >./spor/taytv.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@TayTvOfficial/live)
        EOL

    - name: Get AHaber
      run: |
        touch ./haber/ahaber.m3u8
        sudo cat >./haber/ahaber.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/ahaber/live)
        EOL

    - name: Get APara
      run: |
        touch ./haber/apara.m3u8
        sudo cat >./haber/apara.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/channel/UCzrGg6iyRDuUSnO0cQ5oLcA/live)
        EOL

    - name: Get CNNTurk
      run: |
        touch ./haber/cnnturk.m3u8
        sudo cat >./haber/cnnturk.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/live/bdDfLLy9Y5k?feature=shared)
        EOL

    - name: Get Sirinler
      run: |
        touch ./cocuk/sirinler.m3u8
        sudo cat >./cocuk/sirinler.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@sirinler/live)
        EOL

    - name: Get FirePlace
      run: |
        touch ./other/fireplace.m3u8
        sudo cat >./other/fireplace.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@FobosPlanet/live)
        EOL

    - name: Get Ocean
      run: |
        touch ./other/ocean.m3u8
        sudo cat >./other/ocean.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@Relax321Relaxing/live)
        EOL

    - name: Get SnowStorm
      run: |
        touch ./other/snowstorm.m3u8
        sudo cat >./other/snowstorm.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@purerelaxingvibes/live)
        EOL

    - name: Get RelaxingMusic
      run: |
        touch ./other/relaxingmusic.m3u8
        sudo cat >./other/relaxingmusic.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp --print urls https://www.youtube.com/@timjanis/live)
        EOL

    - name: git add
      run: |
        git add -A
        ls -la

    - name: commit & push
      run: |
        git commit -m "links are updated"
        git push
